name: wann
channels:
  - defaults
dependencies:
  - ca-certificates=2021.7.5=haa95532_1
  - certifi=2021.5.30=py38haa95532_0
  - openssl=1.1.1k=h2bbff1b_0
  - pip=21.1.3=py38haa95532_0
  - python=3.8.10=hdbf39b2_7
  - setuptools=52.0.0=py38haa95532_0
  - sqlite=3.36.0=h2bbff1b_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.36.2=pyhd3eb1b0_0
  - wincertstore=0.2=py38_0
  - pip:
    - absl-py==0.13.0
    - adaptation==0.2.0
    - anyio==3.2.1
    - argon2-cffi==20.1.0
    - astunparse==1.6.3
    - async-generator==1.10
    - attrs==21.2.0
    - babel==2.9.1
    - backcall==0.2.0
    - bleach==3.3.0
    - cachetools==4.2.2
    - cffi==1.14.6
    - charset-normalizer==2.0.1
    - click==8.0.1
    - colorama==0.4.4
    - cvxopt==1.2.6
    - cycler==0.10.0
    - debugpy==1.3.0
    - decorator==5.0.9
    - defusedxml==0.7.1
    - entrypoints==0.3
    - flatbuffers==1.12
    - gast==0.4.0
    - google-auth==1.32.1
    - google-auth-oauthlib==0.4.4
    - google-pasta==0.2.0
    - grpcio==1.34.1
    - h5py==3.1.0
    - idna==3.2
    - ipykernel==6.0.1
    - ipython==7.25.0
    - ipython-genutils==0.2.0
    - jedi==0.18.0
    - jinja2==3.0.1
    - joblib==1.0.1
    - json5==0.9.6
    - jsonschema==3.2.0
    - jupyter-client==6.1.12
    - jupyter-core==4.7.1
    - jupyter-server==1.9.0
    - jupyterlab==3.0.16
    - jupyterlab-pygments==0.1.2
    - jupyterlab-server==2.6.1
    - keras-nightly==2.5.0.dev2021032900
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.1
    - markdown==3.3.4
    - markupsafe==2.0.1
    - matplotlib==3.4.2
    - matplotlib-inline==0.1.2
    - mistune==0.8.4
    - nbclassic==0.3.1
    - nbclient==0.5.3
    - nbconvert==6.1.0
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - nltk==3.6.2
    - notebook==6.4.0
    - numpy==1.19.5
    - oauthlib==3.1.1
    - opt-einsum==3.3.0
    - packaging==21.0
    - pandas==1.3.0
    - pandocfilters==1.4.3
    - parso==0.8.2
    - pickleshare==0.7.5
    - pillow==8.3.1
    - prometheus-client==0.11.0
    - prompt-toolkit==3.0.19
    - protobuf==3.17.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - pygments==2.9.0
    - pyparsing==2.4.7
    - pyrsistent==0.18.0
    - python-dateutil==2.8.2
    - pytz==2021.1
    - pywin32==225
    - pywinpty==1.1.3
    - pyzmq==22.1.0
    - regex==2021.7.6
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - requests-unixsocket==0.2.0
    - rsa==4.7.2
    - scikit-learn==0.24.2
    - scipy==1.7.0
    - send2trash==1.7.1
    - six==1.15.0
    - sniffio==1.2.0
    - tensorboard==2.5.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.5.0
    - tensorflow-estimator==2.5.0
    - termcolor==1.1.0
    - terminado==0.10.1
    - testpath==0.5.0
    - threadpoolctl==2.2.0
    - tornado==6.1
    - tqdm==4.61.2
    - traitlets==5.0.5
    - typing-extensions==3.7.4.3
    - urllib3==1.26.6
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.1.0
    - werkzeug==2.0.1
    - wrapt==1.12.1

